import 'package:amlystuhub/features/advocacy/data/services/advocacy_services.dart';
import 'package:amlystuhub/features/advocacy/domain/models/advocacy_models.dart';
import 'package:amlystuhub/features/auth/presentation%20/providers/auth_providers.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final advocacyRepositoryProvider = Provider<AdvocacyServices>((ref) {
  return AdvocacyServices(FirebaseFirestore.instance);
});

// -----------------------------------------------------------------------------
// STREAM PROVIDERS (Data Reading)
// -----------------------------------------------------------------------------

/// Fetches active Google Forms surveys for students
final activeSurveysStreamProvider = StreamProvider<List<SurveyModel>>((ref) {
  final repo = ref.watch(advocacyRepositoryProvider);
  return repo.watchActiveSurveys();
});

/// Fetches tickets submitted by the currently authenticated student
final userTicketsStreamProvider = StreamProvider<List<TicketModel>>((ref) {
  final repo = ref.watch(advocacyRepositoryProvider);
  final user = ref.watch(currentUserModelProvider).value;
  if (user == null) return Stream.value([]);
  return repo.watchUserTickets(user.uid);
});

/// Leadership view: Fetches all submitted tickets across the school
final allTicketsStreamProvider = StreamProvider<List<TicketModel>>((ref) {
  final repo = ref.watch(advocacyRepositoryProvider);
  return repo.watchAllTickets();
});

// -----------------------------------------------------------------------------
// CONTROLLERS (State & UI Mutations)
// -----------------------------------------------------------------------------

/// Controller handling student ticket submissions
class TicketSubmissionController extends AsyncNotifier<void> {
  @override
  Future<void> build() async {
    // Initial state is idle (AsyncData with null)
  }

  Future<bool> submitTicket({
    required TicketCategory category,
    required String subject,
    required String description,
    required bool isDiscreet,
  }) async {
    final user = ref.read(currentUserModelProvider).value;
    if (user == null) {
      state = AsyncError(
        'User must be authenticated to submit a report.',
        StackTrace.current,
      );
      return false;
    }

    state = const AsyncLoading();

    final newTicket = TicketModel(
      id: '', // Generated by Firestore
      authorId: user.uid,
      authorName: user.name.isNotEmpty ? user.name : 'Student',
      authorEmail: user.email,
      category: category,
      subject: subject.trim(),
      description: description.trim(),
      isDiscreet: isDiscreet,
      status: TicketStatus.submitted,
      createdAt: DateTime.now(),
    );

    state = await AsyncValue.guard(() async {
      final repo = ref.read(advocacyRepositoryProvider);
      await repo.submitTicket(newTicket);
    });

    return !state.hasError;
  }
}

final ticketSubmissionControllerProvider =
    AsyncNotifierProvider.autoDispose<TicketSubmissionController, void>(
      TicketSubmissionController.new,
    );

/// Controller handling leadership actions (updating status, adding notes)
class TicketManagementController extends AsyncNotifier<void> {
  @override
  Future<void> build() async {}

  Future<bool> updateStatus({
    required String ticketId,
    required TicketStatus newStatus,
    String? internalNote,
  }) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final repo = ref.read(advocacyRepositoryProvider);
      await repo.updateTicketStatus(ticketId, newStatus, internalNote);
    });

    return !state.hasError;
  }
}

final ticketManagementControllerProvider =
    AsyncNotifierProvider.autoDispose<TicketManagementController, void>(
      TicketManagementController.new,
    );

/// Controller handling creation and management of Google Forms surveys
class SurveyManagementController extends AsyncNotifier<void> {
  @override
  Future<void> build() async {}

  Future<bool> publishSurvey({
    required String title,
    required String description,
    required String googleFormUrl,
    required String targetGrade,
  }) async {
    state = const AsyncLoading();

    final survey = SurveyModel(
      id: '',
      title: title.trim(),
      description: description.trim(),
      googleFormUrl: googleFormUrl.trim(),
      targetGrade: targetGrade,
      isActive: true,
      createdAt: DateTime.now(),
    );

    state = await AsyncValue.guard(() async {
      final repo = ref.read(advocacyRepositoryProvider);
      await repo.createSurvey(survey);
    });

    return !state.hasError;
  }

  Future<bool> toggleSurveyActiveState(String surveyId, bool isActive) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final repo = ref.read(advocacyRepositoryProvider);
      await repo.toggleSurveyStatus(surveyId, isActive);
    });

    return !state.hasError;
  }
}

final surveyManagementControllerProvider =
    AsyncNotifierProvider.autoDispose<SurveyManagementController, void>(
      SurveyManagementController.new,
    );
