// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy2wvJVoDhVRyUit9oeJvMfcRCTr7vkIc',
    appId: '1:833071963483:web:4a4d365a59ab2db09e8e7e',
    messagingSenderId: '833071963483',
    projectId: 'amlystuhub',
    authDomain: 'amlystuhub.firebaseapp.com',
    storageBucket: 'amlystuhub.firebasestorage.app',
    measurementId: 'G-1V1GP3KXTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_tE_t_2DEbb5PERfJco9AUmPIHa75vaw',
    appId: '1:833071963483:android:8b8406717c7dbeae9e8e7e',
    messagingSenderId: '833071963483',
    projectId: 'amlystuhub',
    storageBucket: 'amlystuhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXv8QQQzHHMz2Me7gX49ib6q9HibilPOI',
    appId: '1:833071963483:ios:eb285f64c1acf2929e8e7e',
    messagingSenderId: '833071963483',
    projectId: 'amlystuhub',
    storageBucket: 'amlystuhub.firebasestorage.app',
    iosBundleId: 'com.example.amlystuhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXv8QQQzHHMz2Me7gX49ib6q9HibilPOI',
    appId: '1:833071963483:ios:eb285f64c1acf2929e8e7e',
    messagingSenderId: '833071963483',
    projectId: 'amlystuhub',
    storageBucket: 'amlystuhub.firebasestorage.app',
    iosBundleId: 'com.example.amlystuhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy2wvJVoDhVRyUit9oeJvMfcRCTr7vkIc',
    appId: '1:833071963483:web:c70ba2e3ef4e9c6c9e8e7e',
    messagingSenderId: '833071963483',
    projectId: 'amlystuhub',
    authDomain: 'amlystuhub.firebaseapp.com',
    storageBucket: 'amlystuhub.firebasestorage.app',
    measurementId: 'G-3JJS3KT8RF',
  );
}
