import 'package:amlystuhub/announcements/data/announcement_services.dart';
import 'package:amlystuhub/announcements/domain/models/announcement_models.dart';
import 'package:amlystuhub/announcements/presentation/state/announcement_state.dart';
import 'package:amlystuhub/features/auth/domain/models%20/user_model.dart';
import 'package:amlystuhub/features/auth/domain/models%20/user_role.dart';
import 'package:amlystuhub/features/auth/presentation%20/providers/auth_providers.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_riverpod/legacy.dart';

class AnnouncementController extends StateNotifier<AnnouncementState> {
  final AnnouncementService _service;

  AnnouncementController({required AnnouncementService service})
    : _service = service,
      super(AnnouncementState.initial());

  Future<bool> createAnnouncement({
    required String title,
    required String content,
    required String category,
    required List<int> targetGrades,
    required bool apOnly,
    required UserModel authorId,
    required String authorName,
    required UserRole authorRole,
  }) async {
    state = AnnouncementState.loading();

    try {
      if (title.trim().isEmpty || content.trim().isEmpty) {
        throw 'Title and Content fields cannot be empty.';
      }

      final newAnnouncement = AnnouncementModel(
        id: '', // Generated by Firestore
        title: title.trim(),
        content: content.trim(),
        authorId: authorId,
        authorName: authorName,
        authorRole: authorRole,
        category: category,
        targetGrades: targetGrades,
        apOnly: apOnly,
        createdAt: DateTime.now(),
      );

      await _service.publishAnnouncement(newAnnouncement);

      state = AnnouncementState.success();
      return true;
    } catch (e) {
      state = AnnouncementState.error(e.toString());
      return false;
    }
  }

  Future<void> togglePin({
    required String announcementId,
    required String userId,
    required bool currentlyPinned,
  }) async {
    try {
      await _service.togglePin(announcementId, userId, !currentlyPinned);
    } catch (_) {}
  }

  void resetState() => state = AnnouncementState.initial();
}

final announcementServiceProvider = Provider<AnnouncementService>((ref) {
  return AnnouncementService();
});

final announcementControllerProvider =
    StateNotifierProvider<AnnouncementController, AnnouncementState>((ref) {
      final service = ref.watch(announcementServiceProvider);
      return AnnouncementController(service: service);
    });

final filteredAnnouncementsProvider = StreamProvider<List<AnnouncementModel>>((
  ref,
) {
  final service = ref.watch(announcementServiceProvider);
  final userAsync = ref.watch(currentUserModelProvider);
  final user = userAsync.value;

  if (user == null) return Stream.value([]);

  return service.getStudentAnnouncementsStream(
    userGrade: user.gradeLevel,
    isApStudent: user.isApStudent,
    isSchoolAdmin: user.role == UserRole.stuCoAdmin,
  );
});
