import 'package:amlystuhub/features/announcements/data/announcement_services.dart';
import 'package:amlystuhub/features/announcements/domain/models/announcement_models.dart';
import 'package:amlystuhub/features/announcements/presentation/state/announcement_state.dart';
import 'package:amlystuhub/features/auth/domain/models%20/user_model.dart';
import 'package:amlystuhub/features/auth/domain/models%20/user_role.dart';
import 'package:amlystuhub/features/auth/presentation%20/providers/auth_providers.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_riverpod/legacy.dart';

class AnnouncementController extends StateNotifier<AnnouncementState> {
  final AnnouncementService _service;

  AnnouncementController({required AnnouncementService service})
    : _service = service,
      super(AnnouncementState.initial());

  Future<bool> createAnnouncement({
    required String title,
    required String content,
    required String category,
    required List<int> targetGrades,
    required bool apOnly,
    required String authorId,
    required String authorName,
    required UserRole authorRole,
  }) async {
    state = AnnouncementState.loading();

    try {
      if (title.trim().isEmpty || content.trim().isEmpty) {
        throw 'Title and Content fields cannot be empty.';
      }

      final newAnnouncement = AnnouncementModel(
        id: '', // Generated by Firestore
        title: title.trim(),
        content: content.trim(),
        authorId: authorId,
        authorName: authorName,
        authorRole: authorRole,
        category: category,
        targetGrades: targetGrades,
        apOnly: apOnly,
        createdAt: DateTime.now(),
      );

      await _service.publishAnnouncement(newAnnouncement);

      state = AnnouncementState.success();
      return true;
    } catch (e) {
      state = AnnouncementState.error(e.toString());
      return false;
    }
  }

  Future<void> togglePin({
    required String announcementId,
    required String userId,
    required bool currentlyPinned,
  }) async {
    try {
      await _service.togglePin(announcementId, userId, !currentlyPinned);
    } catch (_) {}
  }

  void resetState() => state = AnnouncementState.initial();
}

final announcementServiceProvider = Provider<AnnouncementService>((ref) {
  return AnnouncementService();
});

final announcementControllerProvider =
    StateNotifierProvider<AnnouncementController, AnnouncementState>((ref) {
      final service = ref.watch(announcementServiceProvider);
      return AnnouncementController(service: service);
    });

final filteredAnnouncementsProvider = StreamProvider<List<AnnouncementModel>>((
  ref,
) {
  final userAsync = ref.watch(currentUserModelProvider);
  final service = ref.watch(announcementServiceProvider);

  return userAsync.when(
    data: (user) {
      if (user == null) return Stream.value([]);

      return service.getAnnouncements().map((announcements) {
        final isPrivilegedUser = user.role == UserRole.stuCoAdmin;

        return announcements.where((announcement) {
          if (isPrivilegedUser) return true;

          final matchesGrade =
              announcement.targetGrades.isEmpty ||
              announcement.targetGrades.contains(user.gradeLevel);

          final matchesAp = !announcement.apOnly || user.isApStudent;

          return matchesGrade && matchesAp;
        }).toList();
      });
    },
    loading: () => const Stream.empty(),
    error: (_, __) => Stream.value([]),
  );
});
