import 'package:amlystuhub/features/academics/data/services/academic_services.dart';
import 'package:amlystuhub/features/academics/domain/models/academic_models.dart';
import 'package:amlystuhub/features/academics/presentation/state/academic_state.dart';
import 'package:amlystuhub/features/auth/presentation%20/providers/auth_providers.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_riverpod/legacy.dart';

class AcademicController extends StateNotifier<AcademicState> {
  final AcademicService _service;
  final Ref _ref;

  AcademicController(this._service, this._ref) : super(AcademicState.initial());

  /// Role check guard helper
  bool _isAuthorized() {
    final user = _ref.read(currentUserModelProvider).value;
    return user != null &&
        user.role.canPublishAnnouncements; // Admin/Leadership permissions
  }

  Future<bool> createCourse({
    required String title,
    required String code,
    required String description,
    required String category,
    int order = 0,
  }) async {
    state = AcademicState.loading();

    try {
      if (!_isAuthorized()) {
        throw 'Unauthorized: Only StuCo leadership can create courses.';
      }
      if (title.trim().isEmpty || code.trim().isEmpty) {
        throw 'Course Title and Code cannot be empty.';
      }

      final newCourse = CourseModel(
        id: '', // Generated by Firestore
        title: title.trim(),
        code: code.trim().toUpperCase(),
        description: description.trim(),
        category: category,
        order: order,
        createdAt: DateTime.now(),
      );

      await _service.addCourse(newCourse);
      state = AcademicState.success();
      return true;
    } catch (e) {
      state = AcademicState.error(e.toString());
      return false;
    }
  }

  // ==========================================
  // UNIT ACTIONS
  // ==========================================

  Future<bool> createUnit({
    required String courseId,
    required int unitNumber,
    required String title,
    required String description,
    int order = 0,
  }) async {
    state = AcademicState.loading();

    try {
      if (!_isAuthorized()) {
        throw 'Unauthorized: Only StuCo leadership can add units.';
      }
      if (title.trim().isEmpty) {
        throw 'Unit Title cannot be empty.';
      }

      final newUnit = UnitModel(
        id: '',
        unitNumber: unitNumber,
        title: title.trim(),
        description: description.trim(),
        order: order,
      );

      await _service.addUnit(courseId, newUnit);
      state = AcademicState.success();
      return true;
    } catch (e) {
      state = AcademicState.error(e.toString());
      return false;
    }
  }

  // ==========================================
  // RESOURCE ACTIONS (GENERAL OR UNIT)
  // ==========================================

  Future<bool> createResource({
    required String courseId,
    String? unitId, // Null = General/Course-wide Resource
    required String title,
    required String url,
    required ResourceType type,
    String? tag,
    int order = 0,
  }) async {
    state = AcademicState.loading();

    try {
      if (!_isAuthorized()) {
        throw 'Unauthorized: Only StuCo leadership can upload resources.';
      }
      if (title.trim().isEmpty || url.trim().isEmpty) {
        throw 'Resource Title and URL are required.';
      }

      final newResource = ResourceModel(
        id: '',
        title: title.trim(),
        url: url.trim(),
        type: type,
        tag: tag?.trim().isEmpty ?? true ? null : tag?.trim(),
        order: order,
        createdAt: DateTime.now(),
      );

      if (unitId != null) {
        await _service.addUnitResource(courseId, unitId, newResource);
      } else {
        await _service.addGeneralResource(courseId, newResource);
      }

      state = AcademicState.success();
      return true;
    } catch (e) {
      state = AcademicState.error(e.toString());
      return false;
    }
  }

  void resetState() {
    state = AcademicState.initial();
  }
}
